version: '3.8'
services:
  app:
    build:
      context: .
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=your_database
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: your_database
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
