//
// Created by anton on 19/07/2024.
//

#ifndef CUSTOMER_SUPPORT_ASSISTANT_BANKREPOSITORY_H
#define CUSTOMER_SUPPORT_ASSISTANT_BANKREPOSITORY_H


class BankRepository {

};


#endif //CUSTOMER_SUPPORT_ASSISTANT_BANKREPOSITORY_H
